openapi: 3.0.3
info:
  title: ChecKafe API
  description: API for ChecKafe - A coffee shop management system.
  version: 1.0.0
  contact:
    name: ChecKafe Support
    email: support@checkafe.com

servers:
  - url: http://localhost:3000/api/v1
    description: Local server
  - url: https://api.checkafe.com/v1/api
    description: Production server (placeholder)

tags:
  - name: Access
    description: User authentication and session management
  - name: Users
    description: User profile and account management (to be implemented)

paths:
  /access/sign-up:
    post:
      tags:
        - Access
      summary: Register a new user
      description: Creates a new customer account for ChecKafe.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpRequest"
      responses:
        "200":
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignUpResponse"
        "400":
          description: Bad request (e.g., email already exists)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /access/sign-in:
    post:
      tags:
        - Access
      summary: Log in a user
      description: Authenticates a user and returns tokens.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInRequest"
      responses:
        "200":
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignInResponse"
        "400":
          description: Bad request (e.g., email not exists, password incorrect)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /access/sign-out:
    post:
      tags:
        - Access
      summary: Log out a user
      description: Logs out a user based on their user ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignOutRequest"
      responses:
        "200":
          description: User logged out successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignOutResponse"
        "400":
          description: Bad request (e.g., userId missing or user not found)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /admin/users:
    get:
      tags:
        - Users
      summary: Get list of users
      description: Retrieves a paginated list of users, optionally filtered by role or active status. Admin only.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Number of users per page
        - in: query
          name: role
          schema:
            type: string
            enum:
              - ADMIN
              - SHOP_OWNER
              - MANAGER
              - STAFF
              - CUSTOMER
          description: Filter by user role
        - in: query
          name: is_active
          schema:
            type: boolean
          description: Filter by active status
      responses:
        "200":
          description: List of users retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetUsersResponse"
        "400":
          description: Bad request (e.g., invalid role)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized (invalid token)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden (not an admin)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    patch:
      tags:
        - Users
      summary: Manage user account (role and status)
      description: Allows an admin to update a user's role and/or active status.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ManageUserRequest"
      responses:
        "200":
          description: User account updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManageUserResponse"
        "400":
          description: Bad request (e.g., user not found, invalid role)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized (invalid token)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden (not an admin)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    SignUpRequest:
      type: object
      required:
        - full_name
        - email
        - password
      properties:
        full_name:
          type: string
          example: "John Doe"
          description: Full name of the user
        email:
          type: string
          format: email
          example: "john.doe@checkafe.com"
          description: Email address of the user
        password:
          type: string
          format: password
          example: "password123"
          description: Password for the account

    SignUpResponse:
      type: object
      properties:
        user:
          $ref: "#/components/schemas/User"
        tokens:
          $ref: "#/components/schemas/Tokens"

    SignInRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "john.doe@checkafe.com"
          description: Email address of the user
        password:
          type: string
          format: password
          example: "password123"
          description: Password for the account
        refreshToken:
          type: string
          nullable: true
          example: null
          description: Optional refresh token for session renewal

    SignInResponse:
      type: object
      properties:
        user:
          $ref: "#/components/schemas/User"
        tokens:
          $ref: "#/components/schemas/Tokens"

    SignOutRequest:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
          example: "507f1f77bcf86cd799439011"
          description: Unique identifier of the user

    SignOutResponse:
      type: object
      properties:
        message:
          type: string
          example: "Logout successful"
          description: Confirmation message

    User:
      type: object
      properties:
        _id:
          type: string
          example: "507f1f77bcf86cd799439011"
          description: Unique identifier of the user
        full_name:
          type: string
          example: "John Doe"
          description: Full name of the user
        email:
          type: string
          format: email
          example: "john.doe@checkafe.com"
          description: Email address of the user
        role:
          type: string
          enum:
            - CUSTOMER
            - STAFF
            - ADMIN
          example: "CUSTOMER"
          description: Role of the user in the system
        phone:
          type: string
          example: "+84987654321"
          description: Phone number of the user
        avatar:
          type: string
          example: "https://example.com/avatar.jpg"
          description: URL to user's avatar image
        points:
          type: number
          example: 100
          description: Loyalty points of the user
        vip_status:
          type: boolean
          example: false
          description: VIP status of the user
        is_active:
          type: boolean
          example: true
          description: Whether the account is active

    Tokens:
      type: object
      properties:
        accessToken:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
          description: JWT access token for authentication
        refreshToken:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
          description: JWT refresh token for renewing access

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Email already exists"
          description: Error message describing the issue
    GetUsersResponse:
      type: object
      properties:
        users:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
                example: "507f1f77bcf86cd799439011"
              full_name:
                type: string
                example: "John Doe"
              email:
                type: string
                example: "john.doe@example.com"
              role:
                type: string
                example: "CUSTOMER"
              is_active:
                type: boolean
                example: true
        metadata:
          type: object
          properties:
            page:
              type: integer
              example: 1
            limit:
              type: integer
              example: 10
            total:
              type: integer
              example: 25
            totalPages:
              type: integer
              example: 3
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
