const USER_ROLE = {
  ADMIN: "ADMIN",
  SHOP_OWNER: "SHOP_OWNER",
  MANAGER: "MANAGER",
  STAFF: "STAFF",
  CUSTOMER: "CUSTOMER",
};

const HEADER = {
  API_KEY: "x-api-key",
  CLIENT_ID: "x-client-id",
  AUTHORIZATION: "authorization",
  REFRESH_TOKEN: "x-refresh-token",
};

const RESERVATION_TYPE = {
  STANDARD: "Standard",
  PRIORITY: "Priority",
};

const RESERVATION_STATUS = {
  PENDING: "Pending",
  CONFIRMED: "Confirmed",
  CANCELLED: "Cancelled",
  COMPLETED: "Completed",
};


const NOTIFICATION_TYPE = {
  RESERVATION_CREATED: "RESERVATION_CREATED",
  RESERVATION_CONFIRMED: "RESERVATION_CONFIRMED",
  RESERVATION_CANCELLED: "RESERVATION_CANCELLED",
  RESERVATION_COMPLETED: "RESERVATION_COMPLETED",
  CHECK_IN: "CHECK_IN",
};

module.exports = {
  USER_ROLE,
  HEADER,
  RESERVATION_TYPE,
  RESERVATION_STATUS,
  NOTIFICATION_TYPE,
};
